# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    
    services:
      pdf-tool:
        image: gkmr/pdf-tools

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: docker run -v $PWD/:/pdf gkmr/pdf-tools pdftoppm -png /pdf/CV.pdf /pdf/output

    - name: Test
      run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
    
    - name: Artifact first page
      uses: actions/upload-artifact@v1
      with:
        name: images
        path: output-1.png
        
    - name: Artifact second page
      uses: actions/upload-artifact@v1
      with:
        name: images
        path: output-2.png

    - name: Make directory
      run: mkdir ./images

    - name: Move images
      run: mv *.png images

    - name: Commit
      uses: zwaldowski/git-commit-action@v1
    
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: $\{{ secrets.GITHUB_TOKEN }}

